# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# SPDX-License-Identifier: BSD-3-Clause

"""把当前 Isaac stage 保存为 scene_v1_latest（从 test_mode 调用）。

复刻布局编辑器 layout_v1_ui._save_v1 的保存核心(导出 USD + manifest + 退避 previous + reproduce +
更新 registry)，但做成可 import(布局编辑器模块顶层有 AppLauncher，不能 import)。受写闸门保护：
内部 authorize_scene_write() -> 写 -> revoke。机器人姿态由调用方在保存前复位 default(本模块不处理)。

只能在 AppLauncher 之后调用(用 omni.usd/pxr)。helper 在调用时延迟 import isaac。
"""

from __future__ import annotations

import json
import shutil
import time
from pathlib import Path

ENV_NS = "/World/envs/env_0"
ACTIVE_USD_NAME = "scene_v1_latest.usd"
ACTIVE_MANIFEST_NAME = "scene_v1_latest.json"
PREVIOUS_USD_NAME = "scene_v1_previous.usd"
PREVIOUS_MANIFEST_NAME = "scene_v1_previous.json"
REPRODUCE_DOC_NAME = "scene_v1_latest.reproduce.md"


def _timestamp() -> str:
    return f"{time.strftime('%Y%m%d_%H%M%S')}_{int((time.time() % 1) * 1000):03d}"


def _value_to_json(value):
    from pxr import Gf

    if value is None:
        return None
    if isinstance(value, (Gf.Vec3d, Gf.Vec3f, Gf.Vec3h)):
        return [float(value[0]), float(value[1]), float(value[2])]
    if isinstance(value, (Gf.Quatd, Gf.Quatf, Gf.Quath)):
        return [float(value.GetReal()), *[float(item) for item in value.GetImaginary()]]
    try:
        return [float(item) for item in value]
    except TypeError:
        return str(value)


def _get_xform_ops(prim) -> dict:
    from pxr import UsdGeom

    xform = UsdGeom.Xformable(prim)
    result = {"translate": [0.0, 0.0, 0.0], "orient_wxyz": [1.0, 0.0, 0.0, 0.0], "scale": [1.0, 1.0, 1.0]}
    for op in xform.GetOrderedXformOps():
        value = _value_to_json(op.Get())
        if op.GetName() == "xformOp:translate":
            result["translate"] = value
        elif op.GetName() == "xformOp:orient":
            result["orient_wxyz"] = value
        elif op.GetName() == "xformOp:scale":
            result["scale"] = value
    return result


def _get_world_transform(prim) -> dict:
    from pxr import Usd, UsdGeom

    matrix = UsdGeom.Xformable(prim).ComputeLocalToWorldTransform(Usd.TimeCode.Default())
    t = matrix.ExtractTranslation()
    q = matrix.ExtractRotationQuat()
    return {
        "translation": [float(t[0]), float(t[1]), float(t[2])],
        "rotation_wxyz": [float(q.GetReal()), *[float(v) for v in q.GetImaginary()]],
    }


def _subtree_asset_refs(prim) -> list:
    from pxr import Usd

    refs = []
    for sub in Usd.PrimRange(prim):
        for spec in sub.GetPrimStack():
            for r in spec.referenceList.GetAddedOrExplicitItems():
                if r.assetPath:
                    refs.append(r.assetPath)
            for r in spec.payloadList.GetAddedOrExplicitItems():
                if r.assetPath:
                    refs.append(r.assetPath)
    seen, out = set(), []
    for a in refs:
        if a not in seen:
            seen.add(a)
            out.append(a)
    return out


# 运行时调试 marker 的根 prim（DebugVisualizer 把抓取/末端坐标轴画在这里）。
# 它们不是场景资产，绝不能 bake 进保存的 USD：否则下次在静态编辑器里会看到一堆“残留”的
# 彩色坐标轴（含已删除物体的），且是死几何不会跟随资产移动。导出前必须先删掉。
_DEBUG_MARKER_PRIM_PATHS = ("/Visuals/SkillRuntime", "/Visuals")


def strip_debug_markers(stage) -> int:
    """从 stage 上删除运行时调试 marker prim（/Visuals/SkillRuntime 等），返回删除个数。

    export 前调用。/Visuals 只在它空了(只装过 SkillRuntime)时才一并删，避免误删别的可视化。
    """
    removed = 0
    sr = stage.GetPrimAtPath("/Visuals/SkillRuntime")
    if sr.IsValid():
        stage.RemovePrim("/Visuals/SkillRuntime")
        removed += 1
    vis = stage.GetPrimAtPath("/Visuals")
    if vis.IsValid() and not list(vis.GetChildren()):
        stage.RemovePrim("/Visuals")
        removed += 1
    if removed:
        print(f"[scene_saver] stripped {removed} debug-marker prim(s) before export.", flush=True)
    return removed


def _iter_layout_prims(stage) -> list:
    from pxr import UsdGeom

    roots = []
    env_prim = stage.GetPrimAtPath(ENV_NS)
    if env_prim.IsValid():
        roots.extend(child for child in env_prim.GetChildren() if child.IsA(UsdGeom.Xformable))
    world_prim = stage.GetPrimAtPath("/World")
    if world_prim.IsValid():
        for child in world_prim.GetChildren():
            path = child.GetPath().pathString
            if path.startswith("/World/envs") or path.startswith("/World/Visuals"):
                continue
            if child.IsA(UsdGeom.Xformable):
                roots.append(child)
    return roots


def _write_reproduce_doc(active_dir: Path, usd_path: Path, objects: list, manifest: dict, ts: str) -> Path:
    lines = [
        "# How to reproduce scene_v1_latest",
        "",
        "> Auto-generated by test_mode_ui Save. Describes the co-located scene_v1_latest.usd.",
        "",
        f"- timestamp: `{ts}`",
        f"- USD: `{usd_path.name}`  | manifest: `{ACTIVE_MANIFEST_NAME}`",
        f"- task: `{manifest.get('task')}`",
        "",
        "## Load",
        "```bash",
        "./isaaclab.sh -p projects/franka_v1_skill_lab/layout_editor/layout_v1_ui.py --num_envs 1 --load_latest_saved",
        "```",
        "",
        "## Objects (local xform)",
        "| prim | type | pos | rot(wxyz) | scale |",
        "|------|------|-----|-----------|-------|",
    ]
    for o in objects:
        xf = o.get("xform") or {}
        def f(v, n=4):
            return "(" + ",".join(f"{float(x):.{n}f}" for x in v) + ")" if v else "n/a"
        lines.append(f"| `{o.get('name')}` | {o.get('type')} | {f(xf.get('translate'))} | "
                     f"{f(xf.get('orient_wxyz'),5)} | {f(xf.get('scale'))} |")
    lines.append("")
    out = (active_dir / REPRODUCE_DOC_NAME).resolve()
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


# 运行时资产名 -> USD prim 名（用于把运行时位姿写回 USD xform）
# 值可为 str 或候选名列表(取 stage 里实际存在的那个)：microwave 成员换成冰箱后 prim 叫 Fridge，
# 没换时叫 Microwave，列两个名让存档自适配。
_POSE_SYNC_MAP = {
    "cabinet": "Cabinet", "microwave": ["Fridge", "Microwave"], "coffee_machine": "CoffeeMachine",
    "cube_1": "Cube_1", "cube_2": "Cube_2", "cube_3": "Cube_3", "knife": "Knife",
    "microwave_stand": "MicrowaveStand", "dishwasher": "Dishwasher", "robot": "Robot",
}


def _set_prim_translate_orient(prim, pos, quat_wxyz) -> None:
    """设 prim 的 xformOp:translate / xformOp:orient（保留 scale），缺则新增。"""
    from pxr import Gf, UsdGeom

    xf = UsdGeom.Xformable(prim)
    ops = {op.GetName(): op for op in xf.GetOrderedXformOps()}
    if "xformOp:translate" in ops:
        ops["xformOp:translate"].Set(Gf.Vec3d(float(pos[0]), float(pos[1]), float(pos[2])))
    else:
        xf.AddTranslateOp().Set(Gf.Vec3d(float(pos[0]), float(pos[1]), float(pos[2])))
    qf = [float(quat_wxyz[0]), float(quat_wxyz[1]), float(quat_wxyz[2]), float(quat_wxyz[3])]
    if "xformOp:orient" in ops:
        cur = ops["xformOp:orient"].Get()
        q = Gf.Quatf(*qf) if isinstance(cur, Gf.Quatf) else Gf.Quatd(*qf)
        ops["xformOp:orient"].Set(q)
    else:
        xf.AddOrientOp().Set(Gf.Quatd(*qf))


def sync_runtime_poses_to_usd(env, stage) -> int:
    """把可动资产的运行时 root 位姿(world->env-local)写回 USD prim 的 xform。

    必须在 stage.Export 之前调用：use_fabric=True 时运行时位姿在 fabric 里，USD xform 还是初始值，
    不同步会导致导出的还是原始布局。返回同步的资产数。
    """
    scene = env.unwrapped.scene
    env_origin = scene.env_origins[0]
    # 固定映射 + 动态额外资产(add_usd_asset 加的 Prop_ 水果，prim 名 == 成员名)
    pose_map = dict(_POSE_SYNC_MAP)
    try:
        for k in scene.keys():
            if str(k).startswith("Prop_"):
                pose_map[k] = k
    except Exception:
        pass
    n = 0
    for name, primname in pose_map.items():
        try:
            if name not in scene.keys():
                continue
            asset = scene[name]
            pos = (asset.data.root_pos_w[0] - env_origin).detach().cpu().tolist()
            quat = asset.data.root_quat_w[0].detach().cpu().tolist()  # (w,x,y,z)
        except Exception:
            continue
        # primname 可为 str 或候选名列表(取 stage 里实际存在的第一个)
        candidates = primname if isinstance(primname, (list, tuple)) else [primname]
        prim = None
        for cand in candidates:
            pr = stage.GetPrimAtPath(f"{ENV_NS}/{cand}")
            if pr.IsValid():
                prim = pr
                break
        if prim is None or not prim.IsValid():
            continue
        try:
            _set_prim_translate_orient(prim, pos, quat)
            n += 1
        except Exception as exc:  # pragma: no cover
            print(f"[scene_saver] pose sync WARNING: {primname}: {exc}", flush=True)
    print(f"[scene_saver] synced {n} runtime asset poses -> USD before export.", flush=True)
    return n


def save_current_stage_as_latest(env=None, active_dir=None, registry_path=None, task_id: str | None = None,
                                 note: str = "Saved by test_mode_ui.", sensors: dict | None = None) -> dict:
    """导出当前 stage 为 scene_v1_latest(.usd/.json) + 退避 previous + reproduce + 更新 registry。

    env 给定时，先把运行时资产位姿写回 USD xform(fabric 模式下必须)，再导出。
    sensors 给定时(含调整后的相机 offset)写进 registry，与资产位姿一起保存。
    """
    import omni.usd
    from pxr import UsdGeom

    from franka_v1_skill_lab.scene import (
        SCHEMA_VERSION, V1_BASE_TASK_ID, V1_OBJECTS, authorize_scene_write,
        default_sensors, revoke_scene_write, update_active_scene,
    )
    from franka_v1_skill_lab.scene.scene_registry import V1_ACTIVE_DIR

    active_dir = Path(active_dir) if active_dir else V1_ACTIVE_DIR
    active_dir.mkdir(parents=True, exist_ok=True)
    task_id = task_id or V1_BASE_TASK_ID

    stage = omni.usd.get_context().get_stage()
    if stage is None:
        raise RuntimeError("No USD stage is open.")

    if env is not None:
        sync_runtime_poses_to_usd(env, stage)

    # 导出前剥掉运行时调试 marker（抓取/末端坐标轴），否则会 bake 进 USD 变成残留死几何。
    strip_debug_markers(stage)

    ts = _timestamp()
    usd_canonical = (active_dir / ACTIVE_USD_NAME).resolve()
    usd_backup = (active_dir / f"scene_v1_{ts}.usd").resolve()
    json_canonical = (active_dir / ACTIVE_MANIFEST_NAME).resolve()

    # 退避 previous
    if usd_canonical.is_file():
        shutil.copy2(usd_canonical, active_dir / PREVIOUS_USD_NAME)
        if json_canonical.is_file():
            shutil.copy2(json_canonical, active_dir / PREVIOUS_MANIFEST_NAME)

    if not stage.Export(str(usd_canonical)):
        raise RuntimeError(f"Failed to export USD: {usd_canonical}")
    stage.Export(str(usd_backup))

    objects = []
    for prim in _iter_layout_prims(stage):
        objects.append({
            "path": prim.GetPath().pathString,
            "name": prim.GetName(),
            "type": prim.GetTypeName(),
            "xform": _get_xform_ops(prim) if prim.IsA(UsdGeom.Xformable) else None,
            "world_transform": _get_world_transform(prim),
            "asset_refs": _subtree_asset_refs(prim),
        })
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "task": task_id,
        "control_mode": "joint",
        "env_root": ENV_NS,
        "up_axis": str(UsdGeom.GetStageUpAxis(stage)),
        "meters_per_unit": float(UsdGeom.GetStageMetersPerUnit(stage)),
        "contract_objects": list(V1_OBJECTS),
        "sensors": sensors if sensors else default_sensors(),
        "restore_contract": {
            "preferred_restore": "Load scene_v1_latest.usd directly.",
            "programmatic_restore": "Recreate each object at path; apply xform translate/orient_wxyz/scale.",
        },
        "objects": objects,
    }
    payload = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    json_canonical.write_text(payload, encoding="utf-8")
    (active_dir / f"scene_v1_{ts}.json").write_text(payload, encoding="utf-8")
    reproduce = _write_reproduce_doc(active_dir, usd_canonical, objects, manifest, ts)

    # 更新 registry（受写闸门保护）
    authorize_scene_write(reason="test_mode_ui save scene")
    try:
        reg = update_active_scene(ACTIVE_USD_NAME, ACTIVE_MANIFEST_NAME, registry_path=registry_path,
                                  note=note, sensors=sensors)
    finally:
        revoke_scene_write()

    print(f"[scene_saver] saved latest: {usd_canonical}", flush=True)
    print(f"[scene_saver]   manifest: {json_canonical} | reproduce: {reproduce} | registry: {reg}", flush=True)
    return {"usd": str(usd_canonical), "manifest": str(json_canonical), "registry": str(reg),
            "objects": [o["name"] for o in objects]}
